name:    AoC
version: 1.0

dependencies:
- base >= 4.7 && < 5
- directory
- containers
- composition
- regex-tdfa
- split
- matrix
- MemoTrie

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans
- -Wno-missing-export-lists

language: GHC2021

default-extensions: LambdaCase

library:
  source-dirs:
    - src

executable:
  main:        Main.hs
  source-dirs: app
  ghc-options:
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - AoC
